---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: document
  path: src/config.json
  label: Config
- type: directory
  path: src/pages
  label: CV
  create: documents
  match: "**/*"
  templates:
  - cv
upload_dir: public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
